CUDA_VISIBLE_DEVICES=1 python run_seq2seq_qa_tamura.py \
  --model_name_or_path ./mt5_trained_kh_2.0/ \
  --test_file ./dataset/test_knowhow/test_v2.4_mar_mod_neo.json \
  --context_column context \
  --question_column question \
  --answer_column answers \
  --do_train False\
  --do_eval False\
  --do_predict True\
  --per_device_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir ./predict_mt5_trained_kh_2.0/ \
  --version_2_with_negative True \
  --predict_with_generate \
  --generation_max_length 384